# Generated by Django 6.0.5 on 2026-05-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_data', '0002_serviceschedule_maintenancelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='odometer',
            field=models.PositiveIntegerField(help_text='Odometer reading at service (km)'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='interval_km',
            field=models.PositiveIntegerField(help_text='Service every X km'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='interval_months',
            field=models.PositiveIntegerField(help_text='Service every X months'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
